// Generated by https://pagedraw.io/pages/6086
import React from 'react';
import './component_1.css';

function render() {
    return <div className="component_1">
        <div className="component_1-0">
            <div className="component_1-component_1">
                <div className="component_1-0-0-0">
                    <div className="component_1-0-0-0-0">
                        <div className="component_1-0-0-0-0-0">
                            <div onClick={this.props.displayForm} className="component_1-rectangle_2">
                                <div className="component_1-0-0-0-0-0-0-0">
                                {console.log("text", this.props.text)}
                                    <div className="component_1-text_2">{this.props.text}</div> </div> </div>
                                    <div>{this.props.formDisplaying !== false && (
                                        <form onSubmit={this.props.addNewTask}>
                                        <input onChange={this.props.handleChange} type="text" name="newTask"/>
                                        <button type="submit" name="submit">Add!</button>
                                    </form>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="component_1-0-0-0-1">
                        <div className="component_1-0-0-0-1-0">
                            <div className="component_1-0-0-0-1-0-0">
                                { this.props.tasks.map((task, i) => {
                                    return <div key={i} className="component_1-rectangle-1">
                                        <div className="component_1-0-0-0-1-0-0-0-0-0">
                                        
                                            <div className="component_1-text-2" >{ task.title }</div>
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                    </div>
                </div>
                <div className="component_1-0-0-1" /> 
            </div>
        </div>

};

export default function(props) {
    return render.apply({props: props});
}